replicaCount: 2

image:
  repository: 646304591001.dkr.ecr.us-east-2.amazonaws.com/samy-ecr-repo
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  hostname: samy.app.com # users will enter this hostname in their browser to access the application.

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"
