---
- name: Configure Jenkins, Docker, and SonarQube on EC2
  hosts: all
  become: yes
  tasks:

    # Install Required Packages
    - name: Install dependencies
      apt:
        name:
          - curl
          - unzip
          - git
          - apt-transport-https
          - ca-certificates
          - gnupg
          - software-properties-common
        state: present
        update_cache: yes

    # Install Docker
    - name: Install Docker
      shell: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sh get-docker.sh
      args:
        creates: /usr/bin/docker

    - name: Add user to Docker group
      user:
        name: ubuntu
        groups: docker
        append: yes
            # Install Jenkins on EC2
    - name: Update and upgrade APT packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: yes

    - name: Install required dependencies
      ansible.builtin.apt:
        name:
          - curl
          - gnupg
        state: present

    - name: Add Jenkins GPG key
      ansible.builtin.shell:
        cmd: |
          curl -fsSL https://pkg.jenkins.io/debian/jenkins.io-2023.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null
      args:
        creates: /usr/share/keyrings/jenkins-keyring.asc

    - name: Add Jenkins repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
        state: present
        filename: jenkins

    - name: Update apt cache after adding Jenkins repo
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Jenkins
      ansible.builtin.apt:
        name: jenkins
        state: present

    - name: Start and enable Jenkins service
      ansible.builtin.systemd:
        name: jenkins
        state: started
        enabled: yes

    - name: Open port 8080 for Jenkins (UFW)
      ansible.builtin.ufw:
        rule: allow
        port: "8080"
        proto: tcp
      when: ansible_os_family == "Debian"

    - name: Get Jenkins initial admin password
      ansible.builtin.command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_admin_password
      changed_when: false

    - name: Display Jenkins initial admin password
      ansible.builtin.debug:
        msg: "Jenkins initial admin password: {{ jenkins_admin_password.stdout }}"


   